"""extend transaction schema

Revision ID: a27257766717
Revises: e87a03ec55fe
Create Date: 2026-03-17 14:56:18.883030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a27257766717'
down_revision: Union[str, Sequence[str], None] = 'e87a03ec55fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fraud_alerts', 'txn_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('fraud_alerts', 'risk_score',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fraud_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('idx_transaction_timestamp', 'transactions', ['timestamp'], unique=False)
    op.create_index('idx_transaction_user', 'transactions', ['user_id'], unique=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'home_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'home_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('idx_transaction_user', table_name='transactions')
    op.drop_index('idx_transaction_timestamp', table_name='transactions')
    op.alter_column('transactions', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fraud_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fraud_alerts', 'risk_score',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fraud_alerts', 'txn_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
