"""extend transactions schema

Revision ID: e87a03ec55fe
Revises: e6962a378bca
Create Date: 2026-03-17 14:55:25.285878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e87a03ec55fe'
down_revision: Union[str, Sequence[str], None] = 'e6962a378bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('city', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('payment_method', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('device_type', sa.String(), nullable=True))
    op.alter_column('transactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('transactions', 'merchant',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'merchant_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('transactions', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'merchant_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'merchant',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('transactions', 'device_type')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'city')
    # ### end Alembic commands ###
